version: "3"
name: le-docker
networks:
  wnknet:
    driver: bridge

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: r9k
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wnknet

  node:
    depends_on:
      - db
    image: "node"
    user: "root"
    working_dir: /src/
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/src/
    networks:
      - wnknet
    command: bash -c 'npm install; cp /src/build/release/obj.target/binding.node /src/util/r9Kodec.node; while !</dev/tcp/db/3306; do sleep 1; done; node index.js'

